name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo pacman -Syu --noconfirm gptfdisk arch-install-scripts git
      - name: Install qemu-user-static-bin from the AUR
        run: >
          git clone https://aur.archlinux.org/qemu-user-static-bin.git
          cd qemu-user-static-bin
          makepkg -si
          cd ..
      - name: Install archliunuxarm-keyring from the AUR
        run: >
          git clone https://aur.archlinux.org/archliunuxarm-keyring.git
          cd archliunuxarm-keyring
          makepkg -si
          cd ..
      - name: Build ODroid image
        run: sudo ./build.py odroid.img
      - name: Compress image
        run: zstd odroid.img
      - name: Publish compressed image
        uses: actions/upload-artifact@v2
        with:
          name: ODroid Image
          path: odroid.img.zst
