name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    strategy:
      matrix:
        platform: [odroid, rpi3, rpi4]
    steps:
      - uses: actions/checkout@v2
      - run: echo -e "[aurto]\nSigLevel = Optional\nServer = https://aur.raccube.net/" >> /etc/pacman.conf
      - name: Install dependencies
        run: pacman -Syu --noconfirm gptfdisk arch-install-scripts git qemu-user-static-bin archlinuxarm-keyring python dosfstools
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Build ODroid image
        run: sudo ./build.py ${{ matrix.platform }} robot-${{ matrix.platform }}.img
      - name: Compress image
        run: zstd robot-${{ matrix.platform }}.img
      - name: Publish compressed image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: robot-${{ matrix.platform }}.img.zst
