name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt repositories
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install -y libarchive-tools curl fdisk qemu-user-static zstd
      - name: Build ODroid image
        run: sudo ./build.sh odroid odroid.img
      - name: Compress image
        run: zstd odroid.img
      - name: Publish compressed image
        uses: actions/upload-artifact@v2
        with:
          name: ODroid Image
          path: odroid.img.zst
